<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="azstorageexp" name="com.bookmyfurniture.testcases.RegisterTest" tests="2" failures="0" timestamp="5 Mar 2020 14:56:51 GMT" time="25.680" errors="1">
  <testcase name="faiTest" time="0.011" classname="com.bookmyfurniture.testcases.RegisterTest">
    <error type="java.lang.AssertionError" message="This test fails">
      <![CDATA[java.lang.AssertionError: This test fails
	at org.testng.Assert.fail(Assert.java:94)
	at com.bookmyfurniture.testcases.RegisterTest.faiTest(RegisterTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- faiTest -->
  <testcase name="registerFurniture" time="25.669" classname="com.bookmyfurniture.testcases.RegisterTest"/>
</testsuite> <!-- com.bookmyfurniture.testcases.RegisterTest -->
